apiVersion: batch/v1
kind: Job
metadata:
  name: k6-container
spec:
  template:
    spec:
      containers:
        - name: k6-container
          image: k6-container
          imagePullPolicy: Never
      restartPolicy: Never
  parallelism: 10
  completions: 10
