apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: username
      name: rabbitmq-auth-secret
      key: username
    - parameter: password
      name: rabbitmq-auth-secret
      key: password
    - parameter: host
      name: rabbitmq-auth-secret
      key: host
